# Generated by Django 5.1.4 on 2025-01-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_form_admin_remove_form_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.response'),
        ),
        migrations.AlterField(
            model_name='response',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.form'),
        ),
    ]
