# Generated by Django 5.1.4 on 2025-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_response_formresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='questions',
            field=models.ManyToManyField(to='api.question'),
        ),
    ]
